"""test

Revision ID: 780007d2c9e5
Revises: 5f648cdb3e3f
Create Date: 2023-04-15 15:29:17.149787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780007d2c9e5'
down_revision = '5f648cdb3e3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
